version: '3.8'

services:
  quantum-backend-simple:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    container_name: quantum-visualizer-simple
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - quantum-network

networks:
  quantum-network:
    driver: bridge