version: '3.8'

services:
  quantum-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: quantum-visualizer-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount for development
      - ./circuits:/app/circuits:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - quantum-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: quantum-visualizer-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - quantum-backend
    restart: unless-stopped
    networks:
      - quantum-network
    profiles:
      - production

networks:
  quantum-network:
    driver: bridge

volumes:
  quantum-data: